### ISSUE TITLE
[App Portal] Review Step Page

### ISSUE THREAD

**Issue by basokant** [hackwestern/hackwestern#118]
<img width="581" alt="image" src="https://github.com/user-attachments/assets/bbb2210d-0d33-4453-b1af-395f77586565">

- display the question answers in the design (see figma for entire page)
- create page in `components/apply/review-form.tsx`
- edit buttons should be links that link to `apply/[step]`.
- submit button should check if the application is complete (status = "PENDING_REVIEW")

**Comment by hunterchen7** [comment]
closed by #187
