### ISSUE TITLE
[Organizer Portal] Collect and Make Organizer User accounts type Organizer on Prod DB

### ISSUE THREAD

**Issue by basokant** [hackwestern/hackwestern#214]
- ask ppl to sign in
- ask them to give them the email that they used
- only reviewers need this (see below)

Cynthia Li Dennis Zhang Sarah Huang Bonnie Qiu William Liu Benjamin Asokanthan Arsalaan Ali Sophia Ma Swathi Thushi jerry Joy Z  + web team

**Comment by hunterchen7** [comment]
got everyone except Sarah

**Comment by ArsalaanAli** [comment]
i got sarah yesterday, so it should be good now
