### ISSUE TITLE
[Hacker Portal] FAQ Page

### ISSUE THREAD

**Issue by ArsalaanAli** [hackwestern/hackwestern#254]
# FAQ Page
## Tasks
* Implement the design from the Figma into the component in "components/live/faq.tsx"
* Create a Typescript object to hold the questions and answers, so we can edit it once we have the actual FAQ
* Use the components from "components/ui/accordion"
* Make sure its mobile responsive

![image](https://github.com/user-attachments/assets/3ba72ab6-6a54-47a9-8bc5-eca71969dbc3)

**Comment by hunterchen7** [comment]
see if FAQ from promo site can be reused
