### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by ArsalaanAli** [hackwestern/hackwestern#3]
# Use NextAuth to setup third party user authentication (login)

- Use the [NextAuth Documentation](https://next-auth.js.org/getting-started/introduction)
-  Setup the Google and GitHub Providers
- Ask @basokant or @ArsalaanAli to get the Client ID and Client Secret for each provider
- Create a very bare bones page on the frontend with 2 buttons to test Google and GitHub login (this should literally just be a blank page with 2 unstyled buttons)

Ask the leads about any questions you may have!

**Comment by hunterchen7** [comment]
hi
