### ISSUE TITLE
Add Build Cache to GitHub Actions

### ISSUE THREAD

**Issue by basokant** [hackwestern/hackwestern#43]
We can cache our builds to speed up CI a bit!

https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions

**Comment by hunterchen7** [comment]
does this also cache installs or just builds?

**Comment by basokant** [comment]
@hunterchen7 https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
We'd need to follow this documentation for caching dependencies

**Comment by hunterchen7** [comment]
> @hunterchen7 [docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) We'd need to follow this documentation for caching dependencies

Let me try to do both

**Comment by basokant** [comment]
thank you senior devops engineer
