### ISSUE TITLE
Reset Password Mutation

### ISSUE THREAD

**Issue by basokant** [hackwestern/hackwestern#7]
# Create a `ResetPasswordToken` table

## Columns

`userId`: references a User in the user table (add a foreign key constraint) (also the primary key)
`token`: random 20 byte long hex string (use `crypto` for this),
`expires`: date when the token expires

# Setup Email SMPT

We used Mailjet last year, check if this is still up (200 emails per day)

# Create a TRPC (public) mutation under a new router `login` called `reset`.

## Inputs
`email` (string): the email address to be reset.

## Detailed Specification

1. Validate that a user with the `email` exists. Fetch the user's id.
2. Delete all resetPasswordTokens with the user's id.
3. Create a new resetPasswordToken linked to the user. Use a random 20 byte long hex string (use `crypto` for this) for the token.
4. Create a reset password token URL to be sent to the user's email (`/login/set-password?token={token}`)
5. Send Reset Password Email with this token URL (use html template from last year for this)
6. Make the token expire after 10 minutes.

** see API route handler from last year's repository https://github.com/hackwestern/hackwestern2023/blob/master/src/pages/api/password-reset.ts

Ask the leads about any questions you may have!

**Comment by LordExodius** [comment]
update
- logic done
- need to add SMTP server and emailing 📧

**Comment by LordExodius** [comment]
Still needs SMTP and email implementation
